name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main  # adjust this according to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: qkdt/hellodocker:latest

      - name: Deploy with docker-compose
        run: docker-compose -f docker-compose.yml up --detach
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
